### ISSUE TITLE
`g.vertices` and `g.faces` are undefined

### ISSUE THREAD

**Issue by jonikorpi** [andreasplesch/aframe-faceset-component#1]
Getting this in A-Frame 0.5.0. Also using aframe-react.

`Uncaught (in promise) TypeError: Cannot read property 'length' of undefined`

Seems to come from here. https://github.com/andreasplesch/aframe-faceset-component/blob/master/index.js#L86

Looks like `g.vertices` and `g.faces` are undefined when the entity is being mounted, or something? The issue seems to go away if you create empty arrays for both of them while they're undefined. I'm guessing that's not a good solution though. :)

Thanks for this great component, by the way! I love that it's almost kinda like SVG polygons, but for Three. :)

**Comment by andreasplesch** [comment]
Thanks. Does this happen without react as well ? The getOrCreateObject3d() call should make sure there is a mesh.geometry. Or maybe a THREE default changed. If you can share a simplistic example, I may be able to spend some time tracking this down.

**Comment by andreasplesch** [comment]
I think aframe is using now a Three which by default creates a BufferGeometry for a Mesh rather than a Geometry. BufferGeometry does not have 
.vertices ...
It should be possible to pass to getOrCreateObject3d a Mesh constructor with a regular Geometry ?
A better solution would be to use BufferGeometry in the component which will take some work.

Glad you find the component useful. It is designed after the x3d IndexedTriangleSet node as an exploration of what it would take to implement x3d on top of aframe.

**Comment by jonikorpi** [comment]
Hey just as an update: I have it on my todo list to cook up a simple example. Just haven't had a chance yet. :)

**Comment by andreasplesch** [comment]
I tried to update to latest aframe and register this is a geometry rather than a component.

https://github.com/andreasplesch/aframe-triangleset-component

(I also added a-triangleset as primitive but using position with this primitive somehow gets superimposed then to all following entities)

**Comment by andreasplesch** [comment]
Ok, the trinagleset geometry primitive should work now. The primitive also works, I just forgot the proper closing tags. I published it on npm as well.

**Comment by andreasplesch** [comment]
ok, I also found a way to replace the initial BufferGeometry with a regular Geometry in this component, which should address this issue, Also added the <a-faceset> primitive for convenience.
https://github.com/andreasplesch/aframe-faceset-component/commit/1f457bacd51fd049bd8bd49c228647cbe348b0f7
